config/routes.rb
Rails.application.routes.draw do
  
  resources :ords do 
    resources :ord_items
  end

  resources :gmapps
 

  # get 'book_offline/index'
  # resources :orders do
  #   resources :ordered_items
  # end
 
  resources :restaurants do
    resources :reviews
    resources :book_offline
    resources :menus
  end
    
  resources :users do
    resources :reviews 
    resources :ords
  end
  resources :reviews

  # get 'home_page/new'
  resources :users, only:[:create, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home_page#new"
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/admin', to: 'admin_panel#index'
  get '/admin/approval', to: 'admin_panel#approval_panel',as:'admin_approval'
  # post '/approved', to: 'reviews#approved', as:"approved"
  # post '/declined', to: 'reviews#declined', as:"declined"
  post '/reviews/:id/edit', to: 'reviews#update'
  get '/user/:id/reviews/check', to: 'reviews#check'
  post '/restaurants/:id/book_offline/new', to: 'book_offline#create'
  get '/user/:id/bookings', to: 'users#appointments', as:'appointments'
  get '/orders/gmpass', to:'orders#gmapss'
  get '/search',to: 'restaurants#search'
  get '/search',to: 'restaurants#search'
  post '/reviews/accept', to: 'reviews#accept'
  get '/filter', to: 'restaurants#search_filter'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/book_off.rb
class BookOff < ApplicationRecord
  # belongs_to :user
  # belongs_to :restaurant_id
end

app/models/gmapp.rb
class Gmapp < ApplicationRecord
end

app/models/hotel.rb
class Hotel < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
end

app/models/ord.rb
class Ord < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_many :ord_items, dependent: :destroy
end

app/models/ord_item.rb
class OrdItem < ApplicationRecord
  belongs_to :ord
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews, dependent: :destroy
    has_many :users, through: :review
    has_many :menus, dependent: :destroy
    has_many_attached :pictures, dependent: :destroy
    has_many :ords, dependent: :destroy

    geocoded_by :address
    after_validation :geocode

    def address
    end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
    after_initialize :set_defaults, unless: :persisted?

    has_secure_password

    has_many :reviews, dependent: :destroy
    has_many :restaurants
    has_many :ords, dependent: :destroy
    has_many :books, dependent: :destroy
    validates :email, presence:true, uniqueness:true,format:{with: /\A\S+@.+\.\S+\z/ }
    validates :password, presence:true
    
    def set_defaults
        self.isadmin= false if self.isadmin.nil?
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  @@search_var
    def index
      if logged_in?
        @restaurant=Restaurant.all
      else
         redirect_to login_path
      end  
    end

    def show
      if logged_in?
        @restaurant=Restaurant.find(params[:id])
      else
          redirect_to login_path
      end   
    end

    def new
      if logged_in? && current_user.isadmin?
        @restaurant=Restaurant.new
      else
         flash[:notice]="Only admins allowed"
          redirect_to login_path
      end   
    end

    def create
      if logged_in? && current_user.isadmin?
        @restaurant=Restaurant.create(params_create)
        if @restaurant.save
            redirect_to @restaurant
        
        else
            render :new, status: :unprocessable_entity
        end
      else
         redirect_to login_path
      end   
    end

    def edit
      if logged_in? && current_user.isadmin?
        @restaurant = Restaurant.find(params[:id])
      else
          redirect_to login_path
      end   
      end
    
      def update
        if logged_in? && current_user.isadmin?
        @restaurant = Restaurant.find(params[:id])
        
        if params[:restaurant][:pictures].present?
          params[:restaurant][:pictures].each do |image|
            @restaurant.pictures.attach(image)
          end
        end
        if @restaurant.update(resturant_params)
          redirect_to @restaurant
        else
          render :edit, status: :unprocessable_entity
        end
      else
         redirect_to login_path
      end  
      end

      def destroy
        @restaurant = Restaurant.find(params[:id])
        @restaurant.destroy
    
        redirect_to restaurants_path, status: :see_other
      end

      def search
        if !logged_in?
          flash[:notice]="Please Signup/Login"
          redirect_to login_path
        end
         
        @searched_item=params[:search]
         @restaurants1= Restaurant.where("name LIKE ?", "%"+params[:search]+"%")
         @restaurants2= Restaurant.near(params[:search],50).order("distance")
         @restaurants3= Restaurant.where("resturant_type LIKE ?", "%"+params[:search]+"%")

         @restaurants= @restaurants1|@restaurants2|@restaurants3
      end
    
      def search_filter
          @search=params[:search]
          @filter= params[:filter]
          if params[:filter] == 'Restaurant'
          @restaurants= Restaurant.where("name LIKE ?", "%"+@search+"%")
          elsif params[:filter] == 'Location'
          @restaurants= Restaurant.near(@search,50).order("distance")
          else 
          @restaurants= Restaurant.where("resturant_type LIKE ?", "%"+@search+"%")
          end
          
          render :search_filter , locals:{search: params[:search], filter: params[:filter]}
      end
    
    private

    def params_create
        params.require(:restaurant).permit(:name,:category,:resturant_type,:latitude,:longitude,pictures: [])
    end

    def resturant_params
        params.require(:restaurant).permit(:name,:category,:resturant_type)
    end
end

app/helpers/gmapps_helper.rb
module GmappsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/ord_items_helper.rb
module OrdItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ords_helper.rb
module OrdsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/restaurants/edit.html.erb

<div class="signUp">
<h1 class="sign-up">Update Information</h1>
<%= form_with model: @restaurant, class:"container form-g" do |form| %>
  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :category %><br>
    <%= form.text_field :category,class:"form-control" %><br>
  </div>

  <div class="form-group">
    <%= form.label :resturant_type %><br>
    <%= form.text_field :resturant_type ,class:"form-control"%><br>
  </div>

  <div class="form-group">
    <%= form.label :latitude %><br>
    <%= form.number_field :latitude,class:"form-control"%>
 </div>

 <div class="form-group">
    <%= form.label :longitude %><br>
    <%= form.number_field :longitude,class:"form-control"%>
 </div>

   <div class="form-group">
    <%= form.label :pictures %><br>
    <%= form.file_field :pictures, multiple: true%>
  </div>

<br/>
  <div class="form-group">
    <%= form.submit class:"btn btn-danger" %>
  </div>
<% end %>
</div>

app/views/restaurants/index.html.erb
<% if flash.any? %>
<% flash.each do |notice, msg|%>
<div class="alert alert-info">
<%= msg%>
</div>
<% end %>
<% end %>


<div class="user-greeting">
  <h1> Restaurants</h1>
 </div>

<div class="rest-cont">
<% @restaurant.each do |r|%>
<div class="card rest-con">
<h3 class="card-header"><%= r.name%></h3>
<div class="card-body">
     <h5 class="card-title"><%= r.category%></h5>
    <%= link_to "More Details", r, class:"btn btn-secondary"%>
</div>
</div>
<br/>
<% end %>
</div>

app/views/restaurants/new.html.erb
<div class="signUp">
<h1 class="sign-up">Register Hotels</h1>
<%= form_with model: @restaurant, class:"container form-g" do |form| %>
  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name ,class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :category %><br>
    <%= form.text_field :category ,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :resturant_type %><br>
    <%= form.text_field :resturant_type ,class:"form-control"%>
  </div>

 <div class="form-group">
    <%= form.label :latitude %><br>
    <%= form.number_field :latitude,class:"form-control"%>
 </div>

 <div class="form-group">
    <%= form.label :longitude %><br>
    <%= form.number_field :longitude,class:"form-control"%>
 </div>

  <div class="form-group">
    <%= form.label :pictures %><br>
    <%= form.file_field :pictures, multiple: true ,class:"form-control"%>
  </div>

 
<br/>
  <div class="form-group">
    <%= form.submit "Create Restaurant", class:"btn btn-danger"%>
  </div>
<% end %>
</div>

app/views/restaurants/search.html.erb
<div class="user-greeting">
  <h1> Restaurants</h1>
 </div>

<%=form_tag '/filter', method: :get, remote: true do |f|%>
  <%= hidden_field_tag "search", params[:search]%>
  <%= hidden_field_tag "filter", "Restaurant"%>
  <%= submit_tag "Apply Filter", class:"btn btn-danger"%>
<% end %>  
<br/>

<br/>
<div class="rest-cont">
<%if !@restaurants.nil?%>
<% @restaurants.each do |r|%>
<div class="card rest-con">
<h3 class="card-header"><%= r.name%></h3>
<div class="card-body">
     <h5 class="card-title"><%= r.category%></h5>
     <%= link_to "More Details", r, class:"btn btn-secondary"%>
</div>
</div>
<br/>
<% end %>
<%end%>
</div>

app/views/restaurants/search_filter.html.erb
<%= render 'layouts/filter' %>

<h3 class="user-greeting">Filtered Results for <%= @filter%> <%= @search%></h3>
<br/>
<div class="rest-cont">
<%if !@restaurants.nil?%>
<% @restaurants.each do |r|%>
<div class="card rest-con">
<h3 class="card-header"><%= r.name%></h3>
<div class="card-body">
     <h5 class="card-title"><%= r.category%></h5>
     <%= link_to "More Details", r, class:"btn btn-secondary"%>
</div>
</div>
<br/>
<% end %>
<%end%>
</div>

app/views/restaurants/show.html.erb
<% if flash.any? %>
<% flash.each do |notice, msg|%>
<div class="alert alert-info">
<%= msg%>
</div>
<% end %>
<% end %>



<div class="card rest-con">
 <h2 class="rest-name"><%= @restaurant.name%><h2>
 <div class="card-body">
   <h3 class="card-title"> Category -:<%= @restaurant.category%></h3>
   <h3 class="card-title">Type -: <%= @restaurant.resturant_type%></h3>
   <%= link_to "See Menu", restaurant_menus_path(@restaurant.id), class:"btn btn-danger" %>
   <%= link_to "Book Table", new_restaurant_book_offline_path(@restaurant.id), class:"btn btn-secondary"%>
 </div>
</div>

<% if current_user.isadmin?%>
<div class="restaurant-admin-p">
<h4 class="card-title">Admin Controls</h4>
<div>
<%= link_to "Update Information", edit_restaurant_path, class:"btn btn-secondary" %>
<%= link_to "Delete Restaurant", restaurant_path(@restaurant),class:"btn btn-danger", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
 </div>                        
 </div>        
<% end %>

<h3 class="card-title restaurant-admin-p"> Images </h3>

<div class="container rest-pics">
<% @restaurant.pictures.each do |picture|%>
  <%= image_tag picture.variant(resize_to_limit: [300,300]).processed%>
<% end %>
</div>

<h3 class="rest-name">Upload Pictures</h3>
<%= form_with model: @restaurant do |form| %>
  <div class="restaurant-admin-p">
    <%= form.file_field :pictures, multiple: true, class:"btn btn-secondary form-pic", required:"required"%>
    <%= form.submit "Upload Pictures", class:"btn btn-primary" %>
  </div> 
<% end %>

<h3 class="rest-name"> Add review about the hotel-: </h3>
<%= form_tag '/reviews', method: :post, remote: :true , class:"ratings form" do |form| %>
  <div class="">
  <div>
     <dd >
     <%= label_tag " Add Ratings"%>
        <%= radio_button_tag "stars",1, id:"star1"%>
        <%= label_tag "star1", "1 star", title:"text"%>
        <%= radio_button_tag "stars",2, id:"star2"%>
        <%= label_tag "star2", "2 stars", title:"text"%>
        <%= radio_button_tag "stars",3, id:"star3"%>
        <%= label_tag "star3", "3 stars", title:"text"%>
        <%= radio_button_tag "stars",4, id:"star4"%>
        <%= label_tag "star4", "4 stars", title:"text"%>
        <%= radio_button_tag "stars",5, id:"star5"%>
        <%= label_tag "star5", "5 stars", title:"text"%>
      </dd>                     
  <br/>
    <%= label_tag "Write Review"%>
    <%= text_field_tag :ratings,nil, class:"form-control-md", required:"required" %>
  </div>
   <br/>
  
 <%= hidden_field_tag :restaurant_id, @restaurant.id%>
 <%= submit_tag "Submit Review", class:"btn btn-danger"%>
<% end %>
  </div>


<h3 class="rest-name"> Reviews on Resturant </h3>
<% @restaurant.reviews.reverse_each do |review| %>
 <% if review.isApproved%>
 <div class="card rest-con">
   <h4 class="card-title">
    <strong>Username:</strong>
    <% @user= User.find(review.user_id)%>
    <%= @user.username %>
   </h4>

   <h4 class="card-title">
    <strong>Comment:</strong>
    <%= review.ratings %>
   </h4>
 
   <div>
   <h4 class="card-title"> Star Rating-: </h4>
   <% review.stars.to_i.times do  %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
  <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
</svg>
<% end %>
</div>

<% if current_user.isadmin? || current_user.id== @user.id%>
<div>
  <%= link_to "Delete",review_path(review),class:"btn btn-danger", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }%>

  </div>
 <% end %>                 
   </div>
  <% end %>
<% end %>
<br/>